export interface ProjectPreview {
  name: string;
  category: string;
  description: string;
  image: string;
  imageAlt: string;
  imageWidth: number;
  imageHeight: number;
  imagePosition?: string;
}

export type ProjectStatus = "demo" | "published";

export interface PortfolioProject extends ProjectPreview {
  id: string;
  status: ProjectStatus;
  href?: string;
}

// Curadoria independente do portfólio: o hero sempre recebe no máximo três cenas.
export const heroProjectPreviews: ProjectPreview[] = [
  {
    name: "Coleção Essencial",
    category: "Academias",
    description:
      "Uma presença digital criada para academias que desejam explicar sua oferta com clareza e transformar interesse em matrículas.",
    image: "/assets/projects/essencial/essencial-academias.png",
    imageAlt: "Coleção Essencial para Academias em tela desktop",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    name: "Coleção Essencial",
    category: "Advocacia",
    description:
      "Posicionamento estruturado para escritórios de advocacia reduzirem dúvidas e levarem o visitante à escolha certa.",
    image: "/assets/projects/essencial/essencial-advocacia.png",
    imageAlt: "Coleção Essencial para Advocacia em tela desktop",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    name: "Coleção Presença",
    category: "Restaurantes",
    description:
      "Uma narrativa construída para destacar o ambiente e atrair o público ideal para o seu restaurante.",
    image: "/assets/projects/presenca/presenca-restaurantes.png",
    imageAlt: "Coleção Presença para Restaurantes em tela desktop",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
];

export const portfolioProjects: PortfolioProject[] = [
  // ESSENCIAL
  {
    id: "essencial-academias",
    status: "published",
    name: "Essencial Academias",
    category: "Coleção Essencial",
    description: "Design focado em conversão para academias e estúdios fitness.",
    image: "/assets/projects/essencial/essencial-academias.png",
    imageAlt: "Coleção Essencial para Academias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-advocacia",
    status: "published",
    name: "Essencial Advocacia",
    category: "Coleção Essencial",
    description: "Elegância e autoridade para escritórios de advocacia.",
    image: "/assets/projects/essencial/essencial-advocacia.png",
    imageAlt: "Coleção Essencial para Advocacia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-clinicas-medicas",
    status: "published",
    name: "Essencial Clínicas Médicas",
    category: "Coleção Essencial",
    description: "Confiança e clareza para clínicas médicas e consultórios.",
    image: "/assets/projects/essencial/essencial-clinicas-medicas.png",
    imageAlt: "Coleção Essencial para Clínicas Médicas",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-contabilidade",
    status: "published",
    name: "Essencial Contabilidade",
    category: "Coleção Essencial",
    description: "Seriedade e competência para escritórios de contabilidade.",
    image: "/assets/projects/essencial/essencial-contabilidade.png",
    imageAlt: "Coleção Essencial para Contabilidade",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-escolas-e-cursos",
    status: "published",
    name: "Essencial Escolas e Cursos",
    category: "Coleção Essencial",
    description: "Apresentação estruturada para atrair novos alunos.",
    image: "/assets/projects/essencial/essencial-escolas-e-cursos.png",
    imageAlt: "Coleção Essencial para Escolas e Cursos",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-estetica",
    status: "published",
    name: "Essencial Estética",
    category: "Coleção Essencial",
    description: "Design atraente para clínicas de estética e bem-estar.",
    image: "/assets/projects/essencial/essencial-estetica.png",
    imageAlt: "Coleção Essencial para Estética",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-imobiliarias",
    status: "published",
    name: "Essencial Imobiliárias",
    category: "Coleção Essencial",
    description: "Foco na apresentação de imóveis e captação de leads.",
    image: "/assets/projects/essencial/essencial-imobiliarias.png",
    imageAlt: "Coleção Essencial para Imobiliárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-odontologia",
    status: "published",
    name: "Essencial Odontologia",
    category: "Coleção Essencial",
    description: "Um sorriso impecável desde o primeiro contato digital.",
    image: "/assets/projects/essencial/essencial-odontologia.png",
    imageAlt: "Coleção Essencial para Odontologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-psicologia",
    status: "published",
    name: "Essencial Psicologia",
    category: "Coleção Essencial",
    description: "Um espaço seguro e profissional para atendimento online e presencial.",
    image: "/assets/projects/essencial/essencial-psicologia.png",
    imageAlt: "Coleção Essencial para Psicologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-restaurantes",
    status: "published",
    name: "Essencial Restaurantes",
    category: "Coleção Essencial",
    description: "Apresentação focada em conversão para delivery e reservas.",
    image: "/assets/projects/essencial/essencial-restaurantes.png",
    imageAlt: "Coleção Essencial para Restaurantes",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-servicos-residenciais",
    status: "published",
    name: "Essencial Serviços Residenciais",
    category: "Coleção Essencial",
    description: "Clareza e confiança para contratação de serviços.",
    image: "/assets/projects/essencial/essencial-servicos-residenciais.png",
    imageAlt: "Coleção Essencial para Serviços Residenciais",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-veterinarias",
    status: "published",
    name: "Essencial Veterinárias",
    category: "Coleção Essencial",
    description: "Cuidado e atenção refletidos no ambiente digital.",
    image: "/assets/projects/essencial/essencial-veterinarias.png",
    imageAlt: "Coleção Essencial para Veterinárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  // PRESENÇA
  {
    id: "presenca-academias",
    status: "published",
    name: "Presença Academias",
    category: "Coleção Presença",
    description: "Visual vibrante e dinâmico para academias.",
    image: "/assets/projects/presenca/presenca-academias.png",
    imageAlt: "Coleção Presença para Academias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-advocacia",
    status: "published",
    name: "Presença Advocacia",
    category: "Coleção Presença",
    description: "Uma presença imponente e tradicional para escritórios.",
    image: "/assets/projects/presenca/presenca-advocacia.png",
    imageAlt: "Coleção Presença para Advocacia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-clinicas-medicas",
    status: "published",
    name: "Presença Clínicas Médicas",
    category: "Coleção Presença",
    description: "Layout limpo e acolhedor para a área da saúde.",
    image: "/assets/projects/presenca/presenca-clinicas-medicas.png",
    imageAlt: "Coleção Presença para Clínicas Médicas",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-contabilidade",
    status: "published",
    name: "Presença Contabilidade",
    category: "Coleção Presença",
    description: "Transparência e modernidade para serviços contábeis.",
    image: "/assets/projects/presenca/presenca-contabilidade.png",
    imageAlt: "Coleção Presença para Contabilidade",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-escolas-e-cursos",
    status: "published",
    name: "Presença Escolas e Cursos",
    category: "Coleção Presença",
    description: "Uma jornada visual inspiradora para o ensino.",
    image: "/assets/projects/presenca/presenca-escolas-e-cursos.png",
    imageAlt: "Coleção Presença para Escolas e Cursos",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-estetica",
    status: "published",
    name: "Presença Estética",
    category: "Coleção Presença",
    description: "Beleza e bem-estar em destaque no seu portfólio digital.",
    image: "/assets/projects/presenca/presenca-estetica.png",
    imageAlt: "Coleção Presença para Estética",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-imobiliarias",
    status: "published",
    name: "Presença Imobiliárias",
    category: "Coleção Presença",
    description: "Valorizando cada imóvel com um layout sofisticado.",
    image: "/assets/projects/presenca/presenca-imobiliarias.png",
    imageAlt: "Coleção Presença para Imobiliárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-odontologia",
    status: "published",
    name: "Presença Odontologia",
    category: "Coleção Presença",
    description: "Destaque para o sorriso e a estrutura do consultório.",
    image: "/assets/projects/presenca/presenca-odontologia.png",
    imageAlt: "Coleção Presença para Odontologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-psicologia",
    status: "published",
    name: "Presença Psicologia",
    category: "Coleção Presença",
    description: "Acolhimento e profissionalismo para profissionais de psicologia.",
    image: "/assets/projects/presenca/presenca-psicologia.png",
    imageAlt: "Coleção Presença para Psicologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-restaurantes",
    status: "published",
    name: "Presença Restaurantes",
    category: "Coleção Presença",
    description: "Experiência visual deliciosa para o setor gastronômico.",
    image: "/assets/projects/presenca/presenca-restaurantes.png",
    imageAlt: "Coleção Presença para Restaurantes",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-servicos-residenciais",
    status: "published",
    name: "Presença Serviços Residenciais",
    category: "Coleção Presença",
    description: "Profissionalismo em destaque para conquistar clientes.",
    image: "/assets/projects/presenca/presenca-servicos-residenciais.png",
    imageAlt: "Coleção Presença para Serviços Residenciais",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-veterinarias",
    status: "published",
    name: "Presença Veterinárias",
    category: "Coleção Presença",
    description: "Uma apresentação empática e profissional para clínicas.",
    image: "/assets/projects/presenca/presenca-veterinarias.png",
    imageAlt: "Coleção Presença para Veterinárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  }
];
