export interface ProjectPreview {
  name: string;
  category: string;
  description: string;
  image: string;
  imageAlt: string;
  imageWidth: number;
  imageHeight: number;
  imagePosition?: string;
}

export type ProjectStatus = "demo" | "published";

export interface PortfolioProject extends ProjectPreview {
  id: string;
  status: ProjectStatus;
  collectionId: string;
  thumbnail?: string;
  imageSrcSet?: string;
  href?: string;
  previewUrl: string;
}

export const projectCollections = [
  { id: "essencial", name: "Coleção Essencial" },
  { id: "presenca", name: "Coleção Presença" },
  { id: "aura", name: "Coleção Aura" },
];

export const collectionPlans = [
  { id: "start", name: "Arche Start", collections: ["essencial", "presenca"] },
  { id: "pro", name: "Arche Pro", collections: ["aura"] },
];

export const portfolioProjects: PortfolioProject[] = [
  // ESSENCIAL
  {
    id: "essencial-academias",
    previewUrl: "/previews/start/essencial/academia/",
    status: "published",
    name: "Essencial Academia",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Design focado em conversão para academias e estúdios fitness.",
    image: "/assets/projects/essencial/essencial-academias.webp",
    thumbnail: "/assets/projects/essencial/essencial-academias-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-academias-480.webp 480w, /assets/projects/essencial/essencial-academias-960.webp 960w, /assets/projects/essencial/essencial-academias.webp 1400w",
    imageAlt: "Coleção Essencial para Academias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-advocacia",
    previewUrl: "/previews/start/essencial/escritorio-de-advocacia/",
    status: "published",
    name: "Essencial Escritório de Advocacia",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Elegância e autoridade para escritórios de advocacia.",
    image: "/assets/projects/essencial/essencial-advocacia.webp",
    thumbnail: "/assets/projects/essencial/essencial-advocacia-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-advocacia-480.webp 480w, /assets/projects/essencial/essencial-advocacia-960.webp 960w, /assets/projects/essencial/essencial-advocacia.webp 1400w",
    imageAlt: "Coleção Essencial para Advocacia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-clinicas-medicas",
    previewUrl: "/previews/start/essencial/clinica-medica/",
    status: "published",
    name: "Essencial Clínica Médica",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Confiança e clareza para clínicas médicas e consultórios.",
    image: "/assets/projects/essencial/essencial-clinicas-medicas.webp",
    thumbnail: "/assets/projects/essencial/essencial-clinicas-medicas-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-clinicas-medicas-480.webp 480w, /assets/projects/essencial/essencial-clinicas-medicas-960.webp 960w, /assets/projects/essencial/essencial-clinicas-medicas.webp 1400w",
    imageAlt: "Coleção Essencial para Clínicas Médicas",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-contabilidade",
    previewUrl: "/previews/start/essencial/escritorio-de-contabilidade/",
    status: "published",
    name: "Essencial Escritório de Contabilidade",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Seriedade e competência para escritórios de contabilidade.",
    image: "/assets/projects/essencial/essencial-contabilidade.webp",
    thumbnail: "/assets/projects/essencial/essencial-contabilidade-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-contabilidade-480.webp 480w, /assets/projects/essencial/essencial-contabilidade-960.webp 960w, /assets/projects/essencial/essencial-contabilidade.webp 1400w",
    imageAlt: "Coleção Essencial para Contabilidade",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-escolas-e-cursos",
    previewUrl: "/previews/start/essencial/escola/",
    status: "published",
    name: "Essencial Escola",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Apresentação estruturada para atrair novos alunos.",
    image: "/assets/projects/essencial/essencial-escolas-e-cursos.webp",
    thumbnail: "/assets/projects/essencial/essencial-escolas-e-cursos-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-escolas-e-cursos-480.webp 480w, /assets/projects/essencial/essencial-escolas-e-cursos-960.webp 960w, /assets/projects/essencial/essencial-escolas-e-cursos.webp 1400w",
    imageAlt: "Coleção Essencial para Escolas e Cursos",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-estetica",
    previewUrl: "/previews/start/essencial/clinica-de-estetica/",
    status: "published",
    name: "Essencial Clínica de Estética",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Design atraente para clínicas de estética e bem-estar.",
    image: "/assets/projects/essencial/essencial-estetica.webp",
    thumbnail: "/assets/projects/essencial/essencial-estetica-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-estetica-480.webp 480w, /assets/projects/essencial/essencial-estetica-960.webp 960w, /assets/projects/essencial/essencial-estetica.webp 1400w",
    imageAlt: "Coleção Essencial para Estética",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-imobiliarias",
    previewUrl: "/previews/start/essencial/imobiliaria/",
    status: "published",
    name: "Essencial Imobiliária",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Foco na apresentação de imóveis e captação de leads.",
    image: "/assets/projects/essencial/essencial-imobiliarias.webp",
    thumbnail: "/assets/projects/essencial/essencial-imobiliarias-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-imobiliarias-480.webp 480w, /assets/projects/essencial/essencial-imobiliarias-960.webp 960w, /assets/projects/essencial/essencial-imobiliarias.webp 1400w",
    imageAlt: "Coleção Essencial para Imobiliárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-odontologia",
    previewUrl: "/previews/start/essencial/clinica-odontologica/",
    status: "published",
    name: "Essencial Clínica Odontológica",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Um sorriso impecável desde o primeiro contato digital.",
    image: "/assets/projects/essencial/essencial-odontologia.webp",
    thumbnail: "/assets/projects/essencial/essencial-odontologia-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-odontologia-480.webp 480w, /assets/projects/essencial/essencial-odontologia-960.webp 960w, /assets/projects/essencial/essencial-odontologia.webp 1400w",
    imageAlt: "Coleção Essencial para Odontologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-psicologia",
    previewUrl: "/previews/start/essencial/consultorio-de-psicologia/",
    status: "published",
    name: "Essencial Consultório de Psicologia",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Um espaço seguro e profissional para atendimento online e presencial.",
    image: "/assets/projects/essencial/essencial-psicologia.webp",
    thumbnail: "/assets/projects/essencial/essencial-psicologia-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-psicologia-480.webp 480w, /assets/projects/essencial/essencial-psicologia-960.webp 960w, /assets/projects/essencial/essencial-psicologia.webp 1400w",
    imageAlt: "Coleção Essencial para Psicologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-restaurantes",
    previewUrl: "/previews/start/essencial/restaurante/",
    status: "published",
    name: "Essencial Restaurante",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Apresentação focada em conversão para delivery e reservas.",
    image: "/assets/projects/essencial/essencial-restaurantes.webp",
    thumbnail: "/assets/projects/essencial/essencial-restaurantes-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-restaurantes-480.webp 480w, /assets/projects/essencial/essencial-restaurantes-960.webp 960w, /assets/projects/essencial/essencial-restaurantes.webp 1400w",
    imageAlt: "Coleção Essencial para Restaurantes",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-servicos-residenciais",
    previewUrl: "/previews/start/essencial/servico-residencial/",
    status: "published",
    name: "Essencial Serviço Residencial",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Clareza e confiança para contratação de serviços.",
    image: "/assets/projects/essencial/essencial-servicos-residenciais.webp",
    thumbnail: "/assets/projects/essencial/essencial-servicos-residenciais-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-servicos-residenciais-480.webp 480w, /assets/projects/essencial/essencial-servicos-residenciais-960.webp 960w, /assets/projects/essencial/essencial-servicos-residenciais.webp 1400w",
    imageAlt: "Coleção Essencial para Serviços Residenciais",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "essencial-veterinarias",
    previewUrl: "/previews/start/essencial/clinica-veterinaria/",
    status: "published",
    name: "Essencial Clínica Veterinária",
    category: "Coleção Essencial",
    collectionId: "essencial",
    description: "Cuidado e atenção refletidos no ambiente digital.",
    image: "/assets/projects/essencial/essencial-veterinarias.webp",
    thumbnail: "/assets/projects/essencial/essencial-veterinarias-480.webp",
    imageSrcSet: "/assets/projects/essencial/essencial-veterinarias-480.webp 480w, /assets/projects/essencial/essencial-veterinarias-960.webp 960w, /assets/projects/essencial/essencial-veterinarias.webp 1400w",
    imageAlt: "Coleção Essencial para Veterinárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  // PRESENÇA
  {
    id: "presenca-academias",
    previewUrl: "/previews/start/presenca/academia/",
    status: "published",
    name: "Presença Academia",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Visual vibrante e dinâmico para academias.",
    image: "/assets/projects/presenca/presenca-academias.webp",
    thumbnail: "/assets/projects/presenca/presenca-academias-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-academias-480.webp 480w, /assets/projects/presenca/presenca-academias-960.webp 960w, /assets/projects/presenca/presenca-academias.webp 1400w",
    imageAlt: "Coleção Presença para Academias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-advocacia",
    previewUrl: "/previews/start/presenca/escritorio-de-advocacia/",
    status: "published",
    name: "Presença Escritório de Advocacia",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Uma presença imponente e tradicional para escritórios.",
    image: "/assets/projects/presenca/presenca-advocacia.webp",
    thumbnail: "/assets/projects/presenca/presenca-advocacia-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-advocacia-480.webp 480w, /assets/projects/presenca/presenca-advocacia-960.webp 960w, /assets/projects/presenca/presenca-advocacia.webp 1400w",
    imageAlt: "Coleção Presença para Advocacia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-clinicas-medicas",
    previewUrl: "/previews/start/presenca/clinica-medica/",
    status: "published",
    name: "Presença Clínica Médica",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Layout limpo e acolhedor para a área da saúde.",
    image: "/assets/projects/presenca/presenca-clinicas-medicas.webp",
    thumbnail: "/assets/projects/presenca/presenca-clinicas-medicas-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-clinicas-medicas-480.webp 480w, /assets/projects/presenca/presenca-clinicas-medicas-960.webp 960w, /assets/projects/presenca/presenca-clinicas-medicas.webp 1400w",
    imageAlt: "Coleção Presença para Clínicas Médicas",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-contabilidade",
    previewUrl: "/previews/start/presenca/escritorio-de-contabilidade/",
    status: "published",
    name: "Presença Escritório de Contabilidade",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Transparência e modernidade para serviços contábeis.",
    image: "/assets/projects/presenca/presenca-contabilidade.webp",
    thumbnail: "/assets/projects/presenca/presenca-contabilidade-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-contabilidade-480.webp 480w, /assets/projects/presenca/presenca-contabilidade-960.webp 960w, /assets/projects/presenca/presenca-contabilidade.webp 1400w",
    imageAlt: "Coleção Presença para Contabilidade",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-escolas-e-cursos",
    previewUrl: "/previews/start/presenca/escola/",
    status: "published",
    name: "Presença Escola",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Uma jornada visual inspiradora para o ensino.",
    image: "/assets/projects/presenca/presenca-escolas-e-cursos.webp",
    thumbnail: "/assets/projects/presenca/presenca-escolas-e-cursos-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-escolas-e-cursos-480.webp 480w, /assets/projects/presenca/presenca-escolas-e-cursos-960.webp 960w, /assets/projects/presenca/presenca-escolas-e-cursos.webp 1400w",
    imageAlt: "Coleção Presença para Escolas e Cursos",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-estetica",
    previewUrl: "/previews/start/presenca/clinica-de-estetica/",
    status: "published",
    name: "Presença Clínica de Estética",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Beleza e bem-estar em destaque no seu portfólio digital.",
    image: "/assets/projects/presenca/presenca-estetica.webp",
    thumbnail: "/assets/projects/presenca/presenca-estetica-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-estetica-480.webp 480w, /assets/projects/presenca/presenca-estetica-960.webp 960w, /assets/projects/presenca/presenca-estetica.webp 1400w",
    imageAlt: "Coleção Presença para Estética",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-imobiliarias",
    previewUrl: "/previews/start/presenca/imobiliaria/",
    status: "published",
    name: "Presença Imobiliária",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Valorizando cada imóvel com um layout sofisticado.",
    image: "/assets/projects/presenca/presenca-imobiliarias.webp",
    thumbnail: "/assets/projects/presenca/presenca-imobiliarias-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-imobiliarias-480.webp 480w, /assets/projects/presenca/presenca-imobiliarias-960.webp 960w, /assets/projects/presenca/presenca-imobiliarias.webp 1400w",
    imageAlt: "Coleção Presença para Imobiliárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-odontologia",
    previewUrl: "/previews/start/presenca/clinica-odontologica/",
    status: "published",
    name: "Presença Clínica Odontológica",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Destaque para o sorriso e a estrutura do consultório.",
    image: "/assets/projects/presenca/presenca-odontologia.webp",
    thumbnail: "/assets/projects/presenca/presenca-odontologia-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-odontologia-480.webp 480w, /assets/projects/presenca/presenca-odontologia-960.webp 960w, /assets/projects/presenca/presenca-odontologia.webp 1400w",
    imageAlt: "Coleção Presença para Odontologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-psicologia",
    previewUrl: "/previews/start/presenca/consultorio-de-psicologia/",
    status: "published",
    name: "Presença Consultório de Psicologia",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Acolhimento e profissionalismo para profissionais de psicologia.",
    image: "/assets/projects/presenca/presenca-psicologia.webp",
    thumbnail: "/assets/projects/presenca/presenca-psicologia-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-psicologia-480.webp 480w, /assets/projects/presenca/presenca-psicologia-960.webp 960w, /assets/projects/presenca/presenca-psicologia.webp 1400w",
    imageAlt: "Coleção Presença para Psicologia",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-restaurantes",
    previewUrl: "/previews/start/presenca/restaurante/",
    status: "published",
    name: "Presença Restaurante",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Experiência visual deliciosa para o setor gastronômico.",
    image: "/assets/projects/presenca/presenca-restaurantes.webp",
    thumbnail: "/assets/projects/presenca/presenca-restaurantes-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-restaurantes-480.webp 480w, /assets/projects/presenca/presenca-restaurantes-960.webp 960w, /assets/projects/presenca/presenca-restaurantes.webp 1400w",
    imageAlt: "Coleção Presença para Restaurantes",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-servicos-residenciais",
    previewUrl: "/previews/start/presenca/servico-residencial/",
    status: "published",
    name: "Presença Serviço Residencial",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Profissionalismo em destaque para conquistar clientes.",
    image: "/assets/projects/presenca/presenca-servicos-residenciais.webp",
    thumbnail: "/assets/projects/presenca/presenca-servicos-residenciais-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-servicos-residenciais-480.webp 480w, /assets/projects/presenca/presenca-servicos-residenciais-960.webp 960w, /assets/projects/presenca/presenca-servicos-residenciais.webp 1400w",
    imageAlt: "Coleção Presença para Serviços Residenciais",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "presenca-veterinarias",
    previewUrl: "/previews/start/presenca/clinica-veterinaria/",
    status: "published",
    name: "Presença Clínica Veterinária",
    category: "Coleção Presença",
    collectionId: "presenca",
    description: "Uma apresentação empática e profissional para clínicas.",
    image: "/assets/projects/presenca/presenca-veterinarias.webp",
    thumbnail: "/assets/projects/presenca/presenca-veterinarias-480.webp",
    imageSrcSet: "/assets/projects/presenca/presenca-veterinarias-480.webp 480w, /assets/projects/presenca/presenca-veterinarias-960.webp 960w, /assets/projects/presenca/presenca-veterinarias.webp 1400w",
    imageAlt: "Coleção Presença para Veterinárias",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "aura-spa",
    previewUrl: "/previews/pro/aura/spa/",
    status: "published",
    name: "Aura Spa",
    category: "Coleção Aura",
    collectionId: "aura",
    description: "Uma experiência acolhedora para spas, tratamentos e bem-estar, com páginas de serviços e blog.",
    image: "/assets/projects/aura/aura-spa.webp",
    thumbnail: "/assets/projects/aura/aura-spa-480.webp",
    imageSrcSet: "/assets/projects/aura/aura-spa-480.webp 480w, /assets/projects/aura/aura-spa-960.webp 960w, /assets/projects/aura/aura-spa.webp 1400w",
    imageAlt: "Coleção Aura para Spa",
    imageWidth: 1400,
    imageHeight: 900,
    imagePosition: "center top",
  },
];
