export interface ProjectPreview {
  name: string;
  category: string;
  description: string;
  image: string;
  imageAlt: string;
  imageWidth: number;
  imageHeight: number;
  imagePosition?: string;
}

export type ProjectStatus = "demo" | "published";

export interface PortfolioProject extends ProjectPreview {
  id: string;
  status: ProjectStatus;
  href?: string;
}

// Curadoria independente do portfólio: o hero sempre recebe no máximo três cenas.
export const heroProjectPreviews: ProjectPreview[] = [
  {
    name: "Arche Labs",
    category: "Landing page comercial",
    description:
      "Uma presença digital criada para explicar a oferta com clareza e transformar interesse em conversa comercial.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Hero da landing page da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
  },
  {
    name: "Arche Pro",
    category: "Apresentação de oferta",
    description:
      "Planos organizados para reduzir dúvida, comparar escopos e levar o visitante à escolha certa.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Seção de planos da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
  },
  {
    name: "Arche Mobile",
    category: "Experiência responsiva",
    description:
      "A mesma narrativa reconstruída para leitura rápida, navegação confortável e ação no celular.",
    image: "/assets/projects/arche-labs/arche-mobile.png",
    imageAlt: "Landing page completa da Arche Labs em tela mobile",
    imageWidth: 390,
    imageHeight: 11907,
    imagePosition: "top center",
  },
];

// Demonstrações temporárias. Substitua cada entrada por um case real sem alterar
// o componente. O status ajuda a distinguir exemplos de trabalhos publicados.
export const portfolioProjects: PortfolioProject[] = [
  {
    id: "impacto-1",
    status: "demo",
    name: "Primeiro impacto",
    category: "Narrativa",
    description: "Uma abertura direta, com proposta clara e dois caminhos de ação.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Hero da landing page da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "oferta-1",
    status: "demo",
    name: "Oferta sem ruído",
    category: "Conversão",
    description: "Escopos e preços organizados para transformar comparação em decisão.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Seção de planos da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "identidade-1",
    status: "demo",
    name: "Identidade em cena",
    category: "Direção visual",
    description: "A marca entra como prova visual sem competir com a mensagem principal.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Identidade da Arche Labs aplicada à landing page",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "right top",
  },
  {
    id: "mensagem-1",
    status: "demo",
    name: "Mensagem direta",
    category: "Conteúdo",
    description: "Título, argumento e ação cabem no primeiro olhar, sem excesso de contexto.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Mensagem principal da landing page da Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "left top",
  },
  {
    id: "planos-1",
    status: "demo",
    name: "Escolha de plano",
    category: "Interação",
    description: "Preço, prazo e escopo permanecem visíveis no momento da escolha.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Comparação de planos da Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "right top",
  },
  {
    id: "comparacao-1",
    status: "demo",
    name: "Comparação clara",
    category: "Arquitetura",
    description: "As diferenças entre ofertas aparecem antes que a dúvida interrompa a decisão.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Estrutura de comparação da oferta Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "left top",
  },
  {
    id: "impacto-2",
    status: "demo",
    name: "Primeiro impacto 2",
    category: "Narrativa",
    description: "Uma abertura direta, com proposta clara e dois caminhos de ação.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Hero da landing page da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "oferta-2",
    status: "demo",
    name: "Oferta sem ruído 2",
    category: "Conversão",
    description: "Escopos e preços organizados para transformar comparação em decisão.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Seção de planos da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "identidade-2",
    status: "demo",
    name: "Identidade em cena 2",
    category: "Direção visual",
    description: "A marca entra como prova visual sem competir com a mensagem principal.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Identidade da Arche Labs aplicada à landing page",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "right top",
  },
  {
    id: "mensagem-2",
    status: "demo",
    name: "Mensagem direta 2",
    category: "Conteúdo",
    description: "Título, argumento e ação cabem no primeiro olhar, sem excesso de contexto.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Mensagem principal da landing page da Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "left top",
  },
  {
    id: "planos-2",
    status: "demo",
    name: "Escolha de plano 2",
    category: "Interação",
    description: "Preço, prazo e escopo permanecem visíveis no momento da escolha.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Comparação de planos da Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "right top",
  },
  {
    id: "comparacao-2",
    status: "demo",
    name: "Comparação clara 2",
    category: "Arquitetura",
    description: "As diferenças entre ofertas aparecem antes que a dúvida interrompa a decisão.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Estrutura de comparação da oferta Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "left top",
  },
  {
    id: "impacto-3",
    status: "demo",
    name: "Primeiro impacto 3",
    category: "Narrativa",
    description: "Uma abertura direta, com proposta clara e dois caminhos de ação.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Hero da landing page da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "oferta-3",
    status: "demo",
    name: "Oferta sem ruído 3",
    category: "Conversão",
    description: "Escopos e preços organizados para transformar comparação em decisão.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Seção de planos da Arche Labs em tela desktop",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "center top",
  },
  {
    id: "identidade-3",
    status: "demo",
    name: "Identidade em cena 3",
    category: "Direção visual",
    description: "A marca entra como prova visual sem competir com a mensagem principal.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Identidade da Arche Labs aplicada à landing page",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "right top",
  },
  {
    id: "mensagem-3",
    status: "demo",
    name: "Mensagem direta 3",
    category: "Conteúdo",
    description: "Título, argumento e ação cabem no primeiro olhar, sem excesso de contexto.",
    image: "/assets/projects/arche-labs/arche-hero.png",
    imageAlt: "Mensagem principal da landing page da Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "left top",
  },
  {
    id: "planos-3",
    status: "demo",
    name: "Escolha de plano 3",
    category: "Interação",
    description: "Preço, prazo e escopo permanecem visíveis no momento da escolha.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Comparação de planos da Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "right top",
  },
  {
    id: "comparacao-3",
    status: "demo",
    name: "Comparação clara 3",
    category: "Arquitetura",
    description: "As diferenças entre ofertas aparecem antes que a dúvida interrompa a decisão.",
    image: "/assets/projects/arche-labs/arche-offer.png",
    imageAlt: "Estrutura de comparação da oferta Arche Labs",
    imageWidth: 1440,
    imageHeight: 900,
    imagePosition: "left top",
  },
];
